apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-external-dns
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/infra/helm-external-dns
    repoURL: git@github.com:think-ahead-technologies/blog-self-hosted-teleport.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true