apiVersion: v2
name: selfhosted-teleport-cluster-nginx-controller
description: A Helm chart for managing nginx-controller installation in the cluster
type: application
version: 0.1.0
appVersion: v1.16.3
dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: "4.12.0"