# clusterissuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: philipp.gerhard@think-ahead.tech
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        azureDNS:
          resourceGroupName: selfhosted-teleport
          subscriptionID: 77e05782-a2f5-457f-8a77-e00e5826a2dd
          hostedZoneName: selfhosted.teleport.think-ahead.tech
          environment: AzurePublicCloud
          managedIdentity:
            clientID: 79860908-28c3-404e-b8c4-6b8d828c3816